### ISSUE TITLE
.NET fails to load when starting VS Code

### ISSUE THREAD

**Issue by lyonsil** [dotnet/vscode-dotnet-runtime#1037]
**Repro steps:**

1. Open VS Code running inside WSL2 Ubuntu, Windows 10 build 19045.3086, dotnet version 7.0.202
VS Code version info:
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

2. "Error acquiring .NET!" error appears
    
**Extension Version:** 1.0.0
**Error Message:** The "file" argument must be of type string. Received an instance of Object
**Error Stack:** TypeError: The "file" argument must be of type string. Received an instance of Object
	at new NodeError (node:internal/errors:387:5)
	at validateString (node:internal/validators:121:11)
	at normalizeSpawnArguments (node:child_process:518:3)
	at Object.spawnSync (node:child_process:786:8)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095661
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1092018
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1091763)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095584
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:37962
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:36621
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:36366)
	at t.callWithErrorHandling (/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:37910)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095578
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1092018
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1091763)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095512
	at e.$vL.h (/home/anonymous/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/workbench/api/node/extensionHostProcess.js:100:64085)
	at e.$vL.g (/home/anonymous/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/workbench/api/node/extensionHostProcess.js:100:63073)
	at e.$vL.executeCommand (/home/anonymous/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/workbench/api/node/extensionHostProcess.js:100:62973)
	at Object.executeCommand (/home/anonymous/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/workbench/api/node/extensionHostProcess.js:118:20971)
	at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/anonymous/.vscode-server/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1010140)
	at Generator.next (<anonymous>)
	at s (/home/anonymous/.vscode-server/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1008463)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)

The requested log file at "~/.vscode-server/data/logs/20230713T121427/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689268472632.txt" is empty.

**Comment by turbcool** [comment]
I have same problem. OpenSuse Tumbleweed with NET 7 installed.

**Comment by baronfel** [comment]
Closing as duplicate.
