### ISSUE TITLE
Error acquiring .NET!

### ISSUE THREAD

**Issue by burtonrodman** [dotnet/vscode-dotnet-runtime#1045]
**Repro steps:**

1. on Windows, open C# project targeting net6.0 
2. reopen in Devcontainer in an SSH host on Ubuntu Server
```
	"name": "C# (.NET)",
	"image": "mcr.microsoft.com/devcontainers/dotnet:0-6.0",
```

**Extension Version:** 1.0.0
**Error Message:** The "file" argument must be of type string. Received an instance of Object
**Error Stack:** TypeError: The "file" argument must be of type string. Received an instance of Object
	at new NodeError (node:internal/errors:387:5)
	at validateString (node:internal/validators:121:11)
	at normalizeSpawnArguments (node:child_process:518:3)
	at Object.spawnSync (node:child_process:786:8)
	at /home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:1095661
	at Generator.next (<anonymous>)
	at /home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:1092018
	at new Promise (<anonymous>)
	at n (/home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:1091763)
	at /home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:1095584
	at /home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:37962
	at Generator.next (<anonymous>)
	at /home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:36621
	at new Promise (<anonymous>)
	at n (/home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:36366)
	at t.callWithErrorHandling (/home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:37910)
	at /home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:1095578
	at Generator.next (<anonymous>)
	at /home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:1092018
	at new Promise (<anonymous>)
	at n (/home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:1091763)
	at /home/anonymous/.anonymous-server/extensions/ms-dotnettools.anonymous-dotnet-runtime-1.6.0/dist/extension.js:2:1095512
	at e.$vL.h (/anonymous/anonymous-server/bin/linux-x64/660393deaaa6d1996740ff4880f1bad43768c814/out/vs/workbench/api/node/extensionHostProcess.js:100:64085)
	at e.$vL.g (/anonymous/anonymous-server/bin/linux-x64/660393deaaa6d1996740ff4880f1bad43768c814/out/vs/workbench/api/node/extensionHostProcess.js:100:63073)
	at e.$vL.executeCommand (/anonymous/anonymous-server/bin/linux-x64/660393deaaa6d1996740ff4880f1bad43768c814/out/vs/workbench/api/node/extensionHostProcess.js:100:62973)
	at Object.executeCommand (/anonymous/anonymous-server/bin/linux-x64/660393deaaa6d1996740ff4880f1bad43768c814/out/vs/workbench/api/node/extensionHostProcess.js:118:20971)
	at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/anonymous/.anonymous-server/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1010140)
	at Generator.next (<anonymous>)
	at s (/home/anonymous/.anonymous-server/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1008463)

The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/vscode/.vscode-server/data/logs/20230714T015756/exthost3/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689302485043.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by burtonrodman** [comment]
note that the above reference log file is empty.

**Comment by Retorikal** [comment]
https://github.com/dotnet/vscode-dotnet-runtime/issues/1007

**Comment by baronfel** [comment]
Closing as duplicate
