### ISSUE TITLE
Failed to download .NET Core tooling 3.1.8

### ISSUE THREAD

**Issue by Astrophizz** [dotnet/vscode-dotnet-runtime#120]
**Repro steps:**

1. Open an ARM template file (azuredeploy.json).
2. .NET Core Tooling output displays 

> Downloading .NET Core tooling version(s) 3.1.8 ................ Error!
Failed to download .NET Core tooling 3.1.8:
unable to start ssh-agent service, error :1058
Error connecting to agent: No such file or directory

> Error!
Dotnet Core Acquisition Failed: undefined
3. Report issue

**Extension Version:** 0.1.2
**Error Message:** Dotnet Core Acquisition Failed: undefined
**Error Stack:** Error: Dotnet Core Acquisition Failed: undefined
	at c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\extension.js:211:111243
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

[DotNetAcquisition1600377816739.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5241990/DotNetAcquisition1600377816739.txt)

**Comment by Astrophizz** [comment]
Upon further investigation of the ssh-agent service error, I discovered that the ssh-agent service was not started. Starting it manually (this required admin permissions) and restarting VS Code allowed it to download the .NET Core tooling. Is the .NET Core Tooling extension supposed to start the service? Does it expect that the user is always running the service?

**Comment by sfoslund** [comment]
Thanks for the detailed repro steps! I haven't seen this bug before, but from the logs it looks like the install scripts are failing and writing

```
unable to start ssh-agent service, error :1058
Error connecting to agent: No such file or directory
```

to stderr. @bozturkMSFT have you seen errors like this with the install script before?
