### ISSUE TITLE
Request textDocument/semanticTokens/range failed.

### ISSUE THREAD

**Issue by ykurihara-git** [dotnet/vscode-dotnet-runtime#1363]
Type: <b>Bug</b>

Infinite Pop-up of bugged warning

Extension version: 1.7.2
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30831758
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by briankung-bpn** [comment]
I'm experiencing this as well.

<details><summary>Click to expand LSP error</summary>

```
Panic context:
> 
version: 0.3.1782-standalone (85fb463fc 2023-12-24)
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/some/path.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "2",
}

thread 'Worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-analyzer-salsa-0.17.0-pre.4/src/interned.rs:107:32:
index out of bounds: the len is 138927 but the index is 4294967039
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: salsa::interned::InternedStorage<Q>::lookup_value
   4: <DB as hir_expand::db::ExpandDatabase>::lookup_intern_syntax_context
   5: hir_expand::mod_path::resolve_crate_root
   6: hir_expand::mod_path::convert_path
   7: hir_expand::mod_path::convert_path
   8: hir_expand::mod_path::convert_path
   9: hir_expand::mod_path::convert_path
  10: hir_def::item_tree::lower::Ctx::lower_macro_call
  11: hir_def::item_tree::lower::Ctx::lower_mod_item
  12: hir_def::item_tree::ItemTree::file_item_tree_query
  13: salsa::Cycle::catch
  14: salsa::derived::slot::Slot<Q,MP>::execute
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  17: <DB as hir_def::db::DefDatabase>::file_item_tree
  18: hir_def::nameres::collector::DefCollector::collect_macro_expansion
  19: hir_def::nameres::collector::collect_defs
  20: hir_def::nameres::DefMap::block_def_map_query
  21: salsa::Cycle::catch
  22: salsa::derived::slot::Slot<Q,MP>::execute
  23: salsa::derived::slot::Slot<Q,MP>::read
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  25: <DB as hir_def::db::DefDatabase>::block_def_map
  26: hir_def::body::lower::ExprCollector::collect_block_
  27: hir_def::body::lower::ExprCollector::maybe_collect_expr
  28: hir_def::body::lower::ExprCollector::collect_stmt
  29: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  30: hir_def::body::lower::ExprCollector::collect_block_
  31: hir_def::body::lower::ExprCollector::maybe_collect_expr
  32: hir_def::body::lower::ExprCollector::collect_stmt
  33: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  34: hir_def::body::lower::ExprCollector::with_label_rib
  35: hir_def::body::lower::ExprCollector::maybe_collect_expr
  36: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  37: <alloc::boxed::Box<[I]> as core::iter::traits::collect::FromIterator<I>>::from_iter
  38: hir_def::body::lower::ExprCollector::maybe_collect_expr
  39: hir_def::body::lower::ExprCollector::collect_block_
  40: hir_def::body::lower::ExprCollector::maybe_collect_expr
  41: hir_def::body::lower::ExprCollector::collect_expr_opt
  42: hir_def::body::lower::lower
  43: hir_def::body::Body::body_with_source_map_query
  44: salsa::Cycle::catch
  45: salsa::derived::slot::Slot<Q,MP>::execute
  46: salsa::derived::slot::Slot<Q,MP>::read
  47: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  48: hir::source_analyzer::SourceAnalyzer::new_for_body
  49: hir::semantics::SemanticsImpl::analyze_impl
  50: ide_db::defs::NameClass::classify
  51: ide::syntax_highlighting::highlight::name_like
  52: ide::syntax_highlighting::traverse
  53: ide::syntax_highlighting::highlight
  54: salsa::Cancelled::catch
  55: rust_analyzer::handlers::request::handle_semantic_tokens_full_delta
  56: std::panicking::try
  57: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 12:00:26 PM] Request textDocument/semanticTokens/full/delta failed.
  Message: request handler panicked: index out of bounds: the len is 138927 but the index is 4294967039
  Code: -32603 
Panic context:
> 
version: 0.3.1782-standalone (85fb463fc 2023-12-24)
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/some/path.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "2",
}

thread 'Worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-analyzer-salsa-0.17.0-pre.4/src/interned.rs:107:32:
index out of bounds: the len is 141486 but the index is 4294967039
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: salsa::interned::InternedStorage<Q>::lookup_value
   4: <DB as hir_expand::db::ExpandDatabase>::lookup_intern_syntax_context
   5: hir_expand::mod_path::resolve_crate_root
   6: hir_expand::mod_path::convert_path
   7: hir_expand::mod_path::convert_path
   8: hir_expand::mod_path::convert_path
   9: hir_expand::mod_path::convert_path
  10: hir_def::item_tree::lower::Ctx::lower_macro_call
  11: hir_def::item_tree::lower::Ctx::lower_mod_item
  12: hir_def::item_tree::ItemTree::file_item_tree_query
  13: salsa::Cycle::catch
  14: salsa::derived::slot::Slot<Q,MP>::execute
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  17: <DB as hir_def::db::DefDatabase>::file_item_tree
  18: hir_def::nameres::collector::DefCollector::collect_macro_expansion
  19: hir_def::nameres::collector::collect_defs
  20: hir_def::nameres::DefMap::block_def_map_query
  21: salsa::Cycle::catch
  22: salsa::derived::slot::Slot<Q,MP>::execute
  23: salsa::derived::slot::Slot<Q,MP>::read
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  25: <DB as hir_def::db::DefDatabase>::block_def_map
  26: hir_def::body::lower::ExprCollector::collect_block_
  27: hir_def::body::lower::ExprCollector::maybe_collect_expr
  28: hir_def::body::lower::ExprCollector::collect_stmt
  29: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  30: hir_def::body::lower::ExprCollector::collect_block_
  31: hir_def::body::lower::ExprCollector::maybe_collect_expr
  32: hir_def::body::lower::ExprCollector::collect_stmt
  33: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  34: hir_def::body::lower::ExprCollector::with_label_rib
  35: hir_def::body::lower::ExprCollector::maybe_collect_expr
  36: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  37: <alloc::boxed::Box<[I]> as core::iter::traits::collect::FromIterator<I>>::from_iter
  38: hir_def::body::lower::ExprCollector::maybe_collect_expr
  39: hir_def::body::lower::ExprCollector::collect_block_
  40: hir_def::body::lower::ExprCollector::maybe_collect_expr
  41: hir_def::body::lower::ExprCollector::collect_expr_opt
  42: hir_def::body::lower::lower
  43: hir_def::body::Body::body_with_source_map_query
  44: salsa::Cycle::catch
  45: salsa::derived::slot::Slot<Q,MP>::execute
  46: salsa::derived::slot::Slot<Q,MP>::read
  47: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  48: hir::source_analyzer::SourceAnalyzer::new_for_body
  49: hir::semantics::SemanticsImpl::analyze_impl
  50: ide_db::defs::NameClass::classify
  51: ide::syntax_highlighting::highlight::name_like
  52: ide::syntax_highlighting::traverse
  53: ide::syntax_highlighting::highlight
  54: salsa::Cancelled::catch
  55: rust_analyzer::handlers::request::handle_semantic_tokens_full_delta
  56: std::panicking::try
  57: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 12:00:26 PM] Request textDocument/semanticTokens/full/delta failed.
  Message: request handler panicked: index out of bounds: the len is 141486 but the index is 4294967039
  Code: -32603 
Panic context:
> fetch_native_diagnostics

thread 'Worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-analyzer-salsa-0.17.0-pre.4/src/interned.rs:107:32:
index out of bounds: the len is 143722 but the index is 4294967039
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: salsa::interned::InternedStorage<Q>::lookup_value
   4: <DB as hir_expand::db::ExpandDatabase>::lookup_intern_syntax_context
   5: hir_expand::mod_path::resolve_crate_root
   6: hir_expand::mod_path::convert_path
   7: hir_expand::mod_path::convert_path
   8: hir_expand::mod_path::convert_path
   9: hir_expand::mod_path::convert_path
  10: hir_def::item_tree::lower::Ctx::lower_macro_call
  11: hir_def::item_tree::lower::Ctx::lower_mod_item
  12: hir_def::item_tree::ItemTree::file_item_tree_query
  13: salsa::Cycle::catch
  14: salsa::derived::slot::Slot<Q,MP>::execute
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  17: <DB as hir_def::db::DefDatabase>::file_item_tree
  18: hir_def::nameres::collector::DefCollector::collect_macro_expansion
  19: hir_def::nameres::collector::collect_defs
  20: hir_def::nameres::DefMap::block_def_map_query
  21: salsa::Cycle::catch
  22: salsa::derived::slot::Slot<Q,MP>::execute
  23: salsa::derived::slot::Slot<Q,MP>::read
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  25: <DB as hir_def::db::DefDatabase>::block_def_map
  26: hir_def::body::lower::ExprCollector::collect_block_
  27: hir_def::body::lower::ExprCollector::maybe_collect_expr
  28: hir_def::body::lower::ExprCollector::collect_stmt
  29: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  30: hir_def::body::lower::ExprCollector::collect_block_
  31: hir_def::body::lower::ExprCollector::maybe_collect_expr
  32: hir_def::body::lower::ExprCollector::collect_stmt
  33: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  34: hir_def::body::lower::ExprCollector::with_label_rib
  35: hir_def::body::lower::ExprCollector::maybe_collect_expr
  36: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  37: <alloc::boxed::Box<[I]> as core::iter::traits::collect::FromIterator<I>>::from_iter
  38: hir_def::body::lower::ExprCollector::maybe_collect_expr
  39: hir_def::body::lower::ExprCollector::collect_block_
  40: hir_def::body::lower::ExprCollector::maybe_collect_expr
  41: hir_def::body::lower::ExprCollector::collect_expr_opt
  42: hir_def::body::lower::lower
  43: hir_def::body::Body::body_with_source_map_query
  44: salsa::Cycle::catch
  45: salsa::derived::slot::Slot<Q,MP>::execute
  46: salsa::derived::slot::Slot<Q,MP>::read
  47: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  48: hir::DefWithBody::diagnostics
  49: hir::ModuleDef::diagnostics
  50: hir::Module::diagnostics
  51: hir::DefWithBody::diagnostics
  52: hir::Module::diagnostics
  53: ide_diagnostics::diagnostics
  54: salsa::Cancelled::catch
  55: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  56: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  57: rust_analyzer::diagnostics::fetch_native_diagnostics
  58: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by baronfel** [comment]
@ykurihara-git this error is coming from rust-analyzer, not vscode-dotnet-runtime. Please open this issue with that project.

**Comment by briankung-bpn** [comment]
Sorry, that was my comment you were responding to (which I deleted) and not @ykurihara-git's. I deleted my comment and moved it to the rust-analyzer project. Please reconsider @ykurihara-git's bug report.

**Comment by baronfel** [comment]
Thanks @briankung-bpn - the GitHub mobile client didn't show that well at all! I'll reopen.

**Comment by baronfel** [comment]
@ykurihara-git can you please provide any other details?
