### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by ValenciaW9** [dotnet/vscode-dotnet-runtime#1720]
### Describe the bug.

Please attach the log file located at /Users/valenciadianewalker/Library/Application Support/Code/logs/20240324T085632/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1711285027397.txt. Note that this file may contain personal data.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.2/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.3~arm64" -Version 8.0.3 -Verbose -Runtime dotnet -Architecture arm64
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 8.0.3
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.2/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.3~arm64" -Version 8.0.3 -Verbose -Runtime dotnet -Architecture arm64
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 8.0.3
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

    at /Users/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Acquisition/DotnetCoreAcquisitionWorker.js:220:23

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS CodeMac: ~/Library/Application Support/Code/logs/

### Reproduction Steps

Mac: ~/Library/Application Support/Code/logs/

### Expected Behavior

Mac: ~/Library/Application Support/Code/logs/

### Exceptions & Errors (if any)

Please attach the log file located at /Users/valenciadianewalker/Library/Application Support/Code/logs/20240324T085632/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1711285027397.txt. Note that this file may contain personal data.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.2/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.3~arm64" -Version 8.0.3 -Verbose -Runtime dotnet -Architecture arm64
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 8.0.3
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.2/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.3~arm64" -Version 8.0.3 -Verbose -Runtime dotnet -Architecture arm64
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 8.0.3
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

    at /Users/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Acquisition/DotnetCoreAcquisitionWorker.js:220:23

### .NET Install Tool Version

8.0.3

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

**Comment by nagilson** [comment]
cc @dotnet/install-scripts-admin PTAL at this failure where 8 0 3 cannot be found.

**Comment by f-alizada** [comment]
@ValenciaW9 thank you for reporting the issue.
Unfortunately, I was not able to reproduce it.
Is there any chance you could help us narrow down the problem:

- Is the problem still reproducible?
- Is the problem reproducible by invoking the script directly (https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) using the same parameters "dotnet-install.sh -InstallDir "/some/path/to/directory/" -Version 8.0.3 -Verbose -Runtime dotnet -Architecture arm64"?
- Are there any logs generated by the dotnet-install scripts that you could share? 

Thank you in advance!
