### ISSUE TITLE
Failed to download .NET 8.0

### ISSUE THREAD

**Issue by atossell91** [dotnet/vscode-dotnet-runtime#1807]
### Describe the bug.

On downloading the VS Code extension, or starting an Avalonia project, I get the error:

Failed to download .NET 8.0

I have tried connecting to a different network. My internet works fine, otherwise on both networks. But the issue persists.

### Please attach log file(s) here if you have any.

[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1716420698208.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/15409770/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1716420698208.txt)

### Reproduction Steps

Just try to install the Avalonia extension from inside VS Code

### Expected Behavior

The Avalonia extension is installed, and finds/downloads the relevant .NET runtime

### Exceptions & Errors (if any)

Error
Failed to download .NET 8.0:
Web Request to https://dot.net/v1/dotnet-install.sh Failed: n[r].split is not a function. Aborting. Stack: TypeError: n[r].split is not a function
	at /home/ant/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/dist/extension.js:2:753548
	at a (/home/ant/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/dist/extension.js:2:753596)
	at Function.s [as headerInterpreter] (/home/ant/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/dist/extension.js:2:698603)
	at n (/home/ant/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/dist/extension.js:2:702699)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Pt.request (/home/ant/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/dist/extension.js:2:748180)
	at Pt.request (/home/ant/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/dist/extension.js:2:748273)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### .NET Install Tool Version

v0.0.31

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.88.1

**Comment by nagilson** [comment]
This is an issue with the axios cache interceptor which we reported and they have a patch out. We released today with the patch.. let me know if this still occurs on v2.0.6.
