### ISSUE TITLE
<!-- IMPORTANT: Please be sure to remove any private information before submitting. -->  Please attach the log file located at c:\Users\axcdi\AppData\Roaming\Code\logs\20240527T020259\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1716800895972.txt. Note that this file may contain personal data.  **Extension Version:** 1.0.0 **Error Message:** No version was defined to install. **Error Stack:** Error: No version was defined to install.     at c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.0.5\src\extension.ts:210:23     at Generator.next (<anonymous>)     at s (c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.0.5\src\DotnetCoreAcquisitionId.ts:6:49)

### ISSUE THREAD

**Issue by QIXIAIEIJI** [dotnet/vscode-dotnet-runtime#1812]
Please attach the log file located at c:\Users\axcdi\AppData\Roaming\Code\logs\20240527T020259\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1716800895972.txt. Note that this file may contain personal data.

**Extension Version:** 1.0.0
**Error Message:** No version was defined to install.
**Error Stack:** Error: No version was defined to install.
    at c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.0.5\src\extension.ts:210:23
    at Generator.next (<anonymous>)
    at s (c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.0.5\src\DotnetCoreAcquisitionId.ts:6:49)
![OIP](https://github.com/dotnet/vscode-dotnet-runtime/assets/165597929/2633c3b9-a315-4565-abab-ef2e495f6926)
"C:\Users\axcdi\OneDrive\Documents\io diagrams\BUY+HACK INTO MY DIAGRAM+"+PERMISION+
FRANCISCO ANTONIO TABOADA+

**Comment by QIXIAIEIJI** [comment]
https://www.useblackbox.io/editor?id=14feac20-fdba-4ce6-bb0c-6d479b723f15

**Comment by QIXIAIEIJI** [comment]
/**
 * +=_-!~|]{6}
 * 
 */6
ROBOT+6
6

|;';';';';';;'';;';';'';
LAUngue +R+|[Q]
{}][|||||||||||]
:}{}|||||||||||||
}{}{}{{|||||||||}}
}{}{}{}||||||||||
|}{}|}{}|}{}|}|
the point {to fount}+{to positive}
_to enter|+_*^6+|}{6}}}|6?\6{}|6||||6?..,6}|{6|
6}
=================================================================================#{6}
6
. STOP PRINT
+
qwertyuioplkjhgfdsa+mnbvcxz
+zxcvbnmasdfghjklqwertyuiop+
poiuytrewqasdfghjklmnbvcxz+
poiuytrewqasdfghjklzxcvbnm
+lkjhgfdsaqwertyuiopmnbvcxz+
poiuytrewqzxcvbnmlkjhgfdsa+poiuytrewqasdfghjklmnbvcxz+
qwertyuioplkjhgfdsazxcvbnm+
lkjhgfdsaqwertyuiopmnbvcxz+
mnbvcxzasdfghjklqwertyuiop+
=poiuytrewqasdfghjklmnbvcxz+
poiuytrewqasdfghjklmnbvcxz+
+=
a b c d e f g h i j k l m n o p q r s t u v w x y z =+
6^TUre
|+_)(*&^%$#@!~|}{POIUYTREWQASDFGHJKL:"?><MNBVCX
})`1234567890-

\|==\

=\
=-\|-
\][poiuytrewq   qw21`=-/** 


etc
enter
 */+stop
   qwertyuiop[]\|
|}{POIUYTREWQASDFGHJKL:"?><MNBVCX\=}]++++=-+}       +++++

**Comment by QIXIAIEIJI** [comment]
[.ShellClassInfo]
LocalizedResourceName=@%SystemRoot%\system32\shell32.dll,-21790
InfoTip=@%SystemRoot%\system32\shell32.dll,-12689
IconResource=%SystemRoot%\system32\imageres.dll,-108
IconFile=%SystemRoot%\system32\shell32.dll
IconIndex=-237





little shell

SEA SHELL || DOUBLE ZEROS {PASTE
}
ENTER|| contorl |||| wINDOW >>>>> shift {window <<<<<
THEN# PHYICAL ANSWER
||THEN #DOUBLE ONE \\PART :: (U.....)

|||||@ R M A 
|PACK (9/10TH $#) *sHIFT ":{}|ENTER<<<<<<PACK|"


parTNERSHIP/#IN HIGHER *PART *IS * LOW #.,./.,?aNd is # a oDD nuMbeR
so dOubLe & t t t |}{ import EmptyState from '@hi-ui/empty-state'}, DOUBLEE <div uk-countdown="date: YYYY-MM-DDThh:mm:ss+00:00">
    <span class="uk-countdown-number uk-countdown-days"></span>
    <span class="uk-countdown-separator">:</span>
    <span class="uk-countdown-number uk-countdown-hours"></span>
    <span class="uk-countdown-separator">:</span>
    <span class="uk-countdown-number uk-countdown-minutes"></span>
    <span class="uk-countdown-separator">:</span>
    <span class="uk-countdown-number uk-countdown-seconds"></span>
</div>@ r m a <div %sO R  uk-height-match="row: false" 


</<h1 class="uk-heading-divider"></h1>
</div
TRIPLE #(909) j : "[Q]"\PASTE
][]
][]
|+<button uk-toggle="target: #/** my-id */; animation: uk-animation-fade; queued: true" type="button"></button>
|+<button uk-toggle="target: #/** my-id */; animation: uk-animation-fade; queued: true" type="button"></button>
<p id="my-id"></p>
<p id="my-id"></p>|

A
ANSWER
":l|}{j
spilt
a{ANSWER TW#o}


Y /// MUTLIBLE !(BY)TWo#
[TWo]+P
G
GT
PO
LK
MN
VF
CG#v
DE
GS
FD#v
DS
DA
DD
code red(breaD)+_#stop printing ++
[.shell..eettcc
}]|stop print.....>>>>>?{.shell}
|


75 (_((EVEN)))-odd OUT OF &@72 +++ ENTER _ {PRESS} _ + GO buttum ONE 
THEN GO BUTTUM TWo+ODD
#then _ EVEN ????????/
Then odd + thewn even + then oddd 
\\\\THEN Odd }{ then _+_ Even 
 THE ODDDDDDDDDDDDDDDSDS|
 THEN 
  ALL THEM aLL THE THEY AQLL RIGHT | LefT A:LL THE:M 000
  }}
  |}{Odds}';./.,<<<<<<<>THEN EVen +- _+ = ther # to |
  EVEN 
   OOOOOODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD{ODD+}

**Comment by QIXIAIEIJI** [comment]
separator

**Comment by QIXIAIEIJI** [comment]
[.ShellClassInfo]
LocalizedResourceName=@%SystemRoot%\system32\shell32.dll,-21790
InfoTip=@%SystemRoot%\system32\shell32.dll,-12689
IconResource=%SystemRoot%\system32\imageres.dll,-108
IconFile=%SystemRoot%\system32\shell32.dll
IconIndex=-237





little shell

SEA SHELL || DOUBLE ZEROS {PASTE
}
ENTER|| contorl |||| wINDOW >>>>> shift {window <<<<<
THEN# PHYICAL ANSWER
||THEN #DOUBLE ONE \\PART :: (U.....)

|||||@ R M A 
|PACK (9/10TH $#) *sHIFT ":{}|ENTER<<<<<<PACK|"


parTNERSHIP/#IN HIGHER *PART *IS * LOW #.,./.,?aNd is # a oDD nuMbeR
so dOubLe & t t t |}{ import EmptyState from '@hi-ui/empty-state'}, DOUBLEE <div uk-countdown="date: YYYY-MM-DDThh:mm:ss+00:00">
    <span class="uk-countdown-number uk-countdown-days"></span>
    <span class="uk-countdown-separator">:</span>
    <span class="uk-countdown-number uk-countdown-hours"></span>
    <span class="uk-countdown-separator">:</span>
    <span class="uk-countdown-number uk-countdown-minutes"></span>
    <span class="uk-countdown-/** separator */">:</span>
    <span class="uk-countdown-number uk-countdown-seconds"></span>
</div>@ r m a <div %sO R  uk-height-match="row: false" 


</<h1 class="uk-heading-divider"></h1>
</div
TRIPLE #(909) j : "[Q]"\PASTE
][]
][]
|+<button uk-toggle="target: #/** my-id */; animation: uk-animation-fade; queued: true" type="button"></button>
|+<button uk-toggle="target: #/** my-id */; animation: uk-animation-fade; queued: true" type="button"></button>
<p id="my-id"></p>
<p id="my-id"></p>|

A
ANSWER
":l|}{j
spilt
a{ANSWER TW#o}


Y /// MUTLIBLE !(BY)TWo#
[TWo]+P
G
GT
PO
LK
MN
VF
CG#v
DE
GS
FD#v
DS
DA
DD
code red(breaD)+_#stop printing ++
[.shell..eettcc
}]|stop print.....>>>>>?{.shell}
|


75 (_((EVEN)))-odd OUT OF &@72 +++ ENTER _ {PRESS} _ + GO buttum ONE 
THEN GO BUTTUM TWo+ODD
#then _ EVEN ????????/
Then odd + thewn even + then oddd 
\\\\THEN Odd }{ then _+_ Even 
 THE ODDDDDDDDDDDDDDDSDS|
 THEN 
  ALL THEM aLL THE THEY AQLL RIGHT | LefT A:LL THE:M 000
  }}
  |}{Odds}';./.,<<<<<<<>THEN EVen +- _+ = ther # to |
  EVEN 
   OOOOOODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD{ODD+}

**Comment by QIXIAIEIJI** [comment]
{
    // Place your snippets for COBOL Directives here. Each snippet is defined under a snippet name and has a prefix, body and 
    // description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
    // $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
    // same ids are connected.
    // Example:
    // "Print to console": {
    // 	"prefix": "log",
    // 	"body": [
    // 		"console.log('$1');",
    // 		"$2"
    // 	],
    // 	"description": "Log output to console"
    // }
}
