### ISSUE TITLE
Error acquiring dotnet: .NET Acquisition Failed: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by pwang347** [dotnet/vscode-dotnet-runtime#1886]
Received error acquiring dotnet. I can confirm that there is no error for v2.0.9, only v2.1.0.

**OS**: Mac Sonoma 14.5
**VS Code version**: 1.92.0-insider
**Extension version**: v2.1.0

Output logs:
```
ms-toolsai.datawrangler requested to download the .NET Runtime.
Downloading .NET version(s) 6.0.32~arm64 ............. Done!
.NET 6.0.32~arm64 executable path: /Users/paulwang/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.32~arm64/dotnet


Error : (DotnetCommandFailed)
Failed to download .NET 6.0.32~arm64:
.NET Acquisition Failed: Cannot read properties of undefined (reading 'includes')
```

**Comment by logavanc** [comment]
Relevant error from the logs seems to be:

```
Error: .NET Acquisition Failed: Cannot read properties of undefined (reading 'includes')
	at y.getErrorOrStringAsEventError (c:\Users\logavanc\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.0\dist\extension.js:2:29266)
	at y.<anonymous> (c:\Users\logavanc\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.0\dist\extension.js:2:26235)
	at Generator.next (<anonymous>)
	at s (c:\Users\logavanc\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.0\dist\extension.js:2:21947)
```

**Comment by 50Wliu** [comment]
From some testing on my team, I think this only happens on VS Code Insider.
Specifically, I hit this on
```
Version: 1.92.0-insider (user setup)
Commit: 4a103b0eea7de96d12fc2cbada846ca7ef4f1298
Date: 2024-07-17T05:03:59.373Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.27658
```

but my stable VS Code version (and my teammates') is fine.

**Comment by Cryptoc1** [comment]
I am also experiencing this error after updating the ".NET Install Tool" extension to `v2.1.0`.

I was able to workaround the error by manually downgrading the extension to `v2.0.9`:
![image](https://github.com/user-attachments/assets/0bdd969e-1f7a-4e35-9594-c36d49320834)

I'm not sure why the tool would be attempting to install `8.0.7` if I already have the sdk+runtimes installed?

**Comment by seangwright** [comment]
I saw this issue with the [ILSpy VS Code extension](https://marketplace.visualstudio.com/items?itemName=icsharpcode.ilspy-vscode).

If I disable the extension that error does not reappear.

I'm using 

VS Code - v1.91.1 (not insiders)
C# DevKit extension - v1.9.8 (pre-release)
C# extension - v2.39.28 (pre-release)
ILSpy VS Code extension - v0.19.0

**Comment by jbevain** [comment]
Seeing the same issue on macOS.

VS Code 1.91.1 (not insiders)
C# Dev Kit 1.8.14
C# 2.34.12

Reverting .NET Install tool to 2.0.9 fixes the issue.

**Comment by nagilson** [comment]
I am working on a fix for this issue we will release today

**Comment by nagilson** [comment]
Fix pending https://github.com/dotnet/vscode-dotnet-runtime/pull/1888

**Comment by nagilson** [comment]
A fix is released, thank you for reporting this issue. 

If you experience this, please migrate to version 2.1.1. 
If you are offline, please stay on version 2.0.9 or revert to it in the meantime.

**Comment by rsgilbert** [comment]
Still getting this issue. 
I notice that it happens when you open a dotnet project when you dont have internet.
If you close VS Code, reconnect to the internet, and reopen the project, then the issue goes away and intellisense is restored.

**Comment by nagilson** [comment]
Interesting, are you on the latest version of the .NET install tool extension? (2.3.6)

**Comment by rsgilbert** [comment]
Hello.
Yes. 

![Image](https://github.com/user-attachments/assets/258985ff-c8b5-47b5-a7f8-53522fa8e078)


All my extensions are up to date. I am running on Windows 11.
.NET Install Tool: 2.3.6
C# extension: 2.80.16
C# Dev Kit extension: 1.20.35

**Comment by Lumbridge** [comment]
~~I'm also experiencing this issue on v3.0.0 (not offline)~~ installing vscode system wide fixed it for me
