### ISSUE TITLE
Concurrent aquire all ASP.NET and aquire all .NET causes ASP.NET acquisition timeout 

### ISSUE THREAD

**Issue by vsccarl** [dotnet/vscode-dotnet-runtime#1922]
### Describe the bug.

From the runtime extension test plan, Run the 'Sample: Acquire all 2.X ASPNET Runtimes Concurrent', but also run `Sample: Acquire all 2.X .NET Runtimes Concurrent` command at the same time.

Running both at the same time causes the ASP.NET acquisition to timout. 

Running the aquire all ASP.NET runtimes again by itself will continue to timeout.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Using the sample extension, run Sample: Concurrently acquire all 2.X ASPNET Core runtimes and Sample: Concurrently acquire all 2.X .NET Core runtimes at the same time (or as close as possible)

### Expected Behavior

All runtimes are successfully installed.

### Exceptions & Errors (if any)

![image](https://github.com/user-attachments/assets/40a7b15d-5430-4a93-bab2-75dd607a366f)

ms-dotnettools.sample-extension: Trying to install .NET 2.1.30~x64~aspnetcore but it already exists. No downloads or changes were made.
ms-dotnettools.sample-extension requested to download the .NET ASP.NET Runtime.
Downloading .NET version(s) 2.0.9~x64~aspnetcore ...ms-dotnettools.sample-extension: Trying to install .NET 2.2.8~x64~aspnetcore but it already exists. No downloads or changes were made.
...
Error : (DotnetAcquisitionInstallError)
Failed to download .NET 2.0.9~x64~aspnetcore:
.NET install timed out.
You should change the timeout if you have a slow connection. See: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#install-script-timeouts.
Our CDN may be blocked in China or experience significant slowdown, in which case you should install .NET manually., MESSAGE: Command failed: powershell.exe -NoProfile -NonInteractive -NoLogo -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; & 'c:\Users\v-sccarl\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.2\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\v-sccarl\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\2.0.9~x64~aspnetcore' -Version 2.0.9 -Verbose -Runtime aspnetcore -Architecture x64 }"
dotnet-install: Downloading from "primary" link has failed with error:
Uri: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404 Downloading from "primary" link has failed with error:
Uri: https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404
dotnet-install: Downloading from "primary" link has failed with error:
Uri: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404 Downloading from "primary" link has failed with error:
Uri: https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404
Could not find "ASP.NET Core Runtime" with version = 2.0.9
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET support
At C:\Users\v-sccarl\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.2\dist\install 
scripts\dotnet-install.ps1:1330 char:5
+     throw "Could not find `"$assetName`" with version = $($DownloadLi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...on .NET support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find "ASP.NET Core Runtime" with version = 2.0.9
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET support
 
, CODE: 1, SIGNAL: null

Error : (DotnetCommandFailed)
Failed to download .NET 2.0.9~x64~aspnetcore:
.NET Acquisition Failed: .NET install timed out.
You should change the timeout if you have a slow connection. See: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#install-script-timeouts.
Our CDN may be blocked in China or experience significant slowdown, in which case you should install .NET manually., MESSAGE: Command failed: powershell.exe -NoProfile -NonInteractive -NoLogo -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; & 'c:\Users\v-sccarl\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.2\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\v-sccarl\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\2.0.9~x64~aspnetcore' -Version 2.0.9 -Verbose -Runtime aspnetcore -Architecture x64 }"
dotnet-install: Downloading from "primary" link has failed with error:
Uri: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404 Downloading from "primary" link has failed with error:
Uri: https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404
dotnet-install: Downloading from "primary" link has failed with error:
Uri: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404 Downloading from "primary" link has failed with error:
Uri: https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404
Could not find "ASP.NET Core Runtime" with version = 2.0.9
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET support
At C:\Users\v-sccarl\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.2\dist\install 
scripts\dotnet-install.ps1:1330 char:5
+     throw "Could not find `"$assetName`" with version = $($DownloadLi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...on .NET support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find "ASP.NET Core Runtime" with version = 2.0.9
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET support
 
, CODE: 1, SIGNAL: null, Error: .NET install timed out.
You should change the timeout if you have a slow connection. See: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#install-script-timeouts.
Our CDN may be blocked in China or experience significant slowdown, in which case you should install .NET manually., MESSAGE: Command failed: powershell.exe -NoProfile -NonInteractive -NoLogo -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; & 'c:\Users\v-sccarl\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.2\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\v-sccarl\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\2.0.9~x64~aspnetcore' -Version 2.0.9 -Verbose -Runtime aspnetcore -Architecture x64 }"
dotnet-install: Downloading from "primary" link has failed with error:
Uri: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404 Downloading from "primary" link has failed with error:
Uri: https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404
dotnet-install: Downloading from "primary" link has failed with error:
Uri: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404 Downloading from "primary" link has failed with error:
Uri: https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip
StatusCode: 404
Error: Unable to download https://dotnetbuilds.azureedge.net/public/aspnetcore/Runtime/2.0.9/aspnetcore-runtime-2.0.9-win-x64.zip. Returned HTTP status code: 404
Could not find "ASP.NET Core Runtime" with version = 2.0.9
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET support
At C:\Users\v-sccarl\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.2\dist\install 
scripts\dotnet-install.ps1:1330 char:5
+     throw "Could not find `"$assetName`" with version = $($DownloadLi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...on .NET support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find "ASP.NET Core Runtime" with version = 2.0.9
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET support
 
, CODE: 1, SIGNAL: null
	at f.<anonymous> (c:\Users\v-sccarl\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.2\dist\extension.js:2:22739)
	at Generator.next (<anonymous>)
	at s (c:\Users\v-sccarl\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.2\dist\extension.js:2:20318)

### .NET Install Tool Version

2.1.2

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.92.2

**Comment by nagilson** [comment]
Thank you for this report. 

Well I feel a bit silly because version 2.0.9 of aspnet does not even exist. That is why it's timing out, I'm pretty sure... We need to update this command ;
