### ISSUE TITLE
Error: Please provide instrumentation key

### ISSUE THREAD

**Issue by digama0** [dotnet/vscode-dotnet-runtime#1958]
### Describe the bug.

I'm not sure why this extension is installed as I don't use .NET, but it reports an error to the console on startup:

```
Error: Please provide instrumentation key
	at ue (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:382196)
	at /home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:305992
	at Object.m [as use] (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:297462)
	at /home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:296806
	at s.<computed> [as watch] (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:296817)
	at e.<computed> [as initialize] (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:305780)
	at e.n [as initialize] (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:374092)
	at i (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:372019)
	at /home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:372089
	at L (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:375051)
	at new e (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:371471)
	at t.appInsightsClientFactory (/home/mario/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6/dist/extension.js:2:393101) {stack: 'Error: Please provide instrumentation key
	at…net-runtime-2.1.6/dist/extension.js:2:393101)', message: 'Please provide instrumentation key'}
```

I have no idea what it's talking about, and there are almost no hits for this error message online. I don't want to instrument anything.

### Please attach log file(s) here if you have any.

nothing interesting:
```
9/24/2024, 6:30:38 PM DotnetWSLCheckEvent
Checking if system is WSL. OS: linux

9/24/2024, 6:30:38 PM DotnetWSLOperationOutputEvent
The output of the WSL check:
stdout: 
stderr: 
status: 1
```

### Reproduction Steps

* Run vscode via [Extension Development Host] and look at the debug console in the host, or look at the console using developer mode
* Unknown additional factors?
* Observe `Error: Please provide instrumentation key`

### Expected Behavior

no error

### .NET Install Tool Version

v2.1.6

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.93.1

**Comment by baronfel** [comment]
@nagilson maybe this is related to the gaps in telemetry you were seeing?

**Comment by nagilson** [comment]
Yeah that checks out, thank you. We do provide an instrumentation key, but they must have changed the requirement :/

@diagma0 This is installed because you use an extension that was probably written in C#. If you try to uninstall the extension itll show you who is using it. Thanks for reporting the issue.

**Comment by janthoXO** [comment]
I get the same error on mac when trying to develop a vscode extension with a webview

**Comment by bookofproofs** [comment]
The same error on Windows when trying to debug a vscode extension using F5.

**Comment by nagilson** [comment]
I am just waiting on someone from the engineering system team to give me permission to create a new key 🥱
