### ISSUE TITLE
Failed to download .NET 8.0.10~x64~aspnetcore when it said it was Done?

### ISSUE THREAD

**Issue by o-o00o-o** [dotnet/vscode-dotnet-runtime#2012]
### Describe the bug.

Get error "Error aquiring .NET!" on vscode start

Log from .NET Install Tool is fairly unhelpful

```
ms-azuretools.vscode-azure-github-copilot requested to download the .NET ASP.NET Runtime.
Downloading .NET version(s) 8.0.10~x64~aspnetcore ........... Done!
.NET 8.0.10~x64~aspnetcore executable path: c:\Users\bgerhardi\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\8.0.10~x64~aspnetcore\dotnet.exe


Error : (DotnetInstallationValidationError)
Failed to download .NET 8.0.10~x64~aspnetcore:
Validation of .dotnet installation for version {"installId":"8.0.10~x64~aspnetcore","version":"8.0.10","architecture":"x64","isGlobal":false,"installMode":"aspnetcore"} failed: Expected installation folder c:\Users\bgerhardi\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\8.0.10~x64~aspnetcore does not exist.


Error : (DotnetCommandFailed)
Failed to download .NET 8.0.10~x64~aspnetcore:
.NET Acquisition Failed: Validation of .dotnet installation for version {"installId":"8.0.10~x64~aspnetcore","version":"8.0.10","architecture":"x64","isGlobal":false,"installMode":"aspnetcore"} failed: Expected installation folder c:\Users\bgerhardi\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\8.0.10~x64~aspnetcore does not exist., Error: Validation of .dotnet installation for version {"installId":"8.0.10~x64~aspnetcore","version":"8.0.10","architecture":"x64","isGlobal":false,"installMode":"aspnetcore"} failed: Expected installation folder c:\Users\bgerhardi\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\8.0.10~x64~aspnetcore does not exist.
    at c.assertOrThrowError (c:\Users\bgerhardi\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\InstallationValidator.js:38:19)
    at c.validateDotnetInstall (c:\Users\bgerhardi\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\InstallationValidator.js:18:18)
    at y.next (c:\Users\bgerhardi\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\DotnetCoreAcquisitionWorker.js:251:43)
    at Generator.next (<anonymous>)
    at s (c:\Users\bgerhardi\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\DotnetCoreAcquisitionWorker.js:5:58)

```

more detailed log attached

### Please attach log file(s) here if you have any.

[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1731059151952.txt](https://github.com/user-attachments/files/17676686/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1731059151952.txt)
The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Open vscode, get error. It has been happeneing for several weeks. computer restart doesn't help

### Expected Behavior

.net updated/installed successfully

### .NET Install Tool Version

 8.0.10

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.95.2 (user setup)

**Comment by nagilson** [comment]
Thank you for taking the time to write a detailed report.
Is it true that c:\Users\YOUR_USERNAME\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\8.0.10~x64~aspnetcore\dotnet.exe does not exist?

Probably if you installed the .NET SDK (using our extension command to install .NET SDK 8.0.1xx) and restart vscode it would get rid of the error for you. Though not fix our bug 😄 
--
@dotnet/install-scripts-maintainers 
```
STDERR:  & : AuthorizationManager check failed.
At line:1 char:137
+ ... ]::Tls12; & 'c:\Users\bgerhardi\.vscode\extensions\ms-dotnettools.vsc ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
If the install script hits this error, will it continue to work? Is this due to a lack of powershell policy? It should be greater than ConstrainedLanguage or NoLanguage which I thought is all that is necessary.

**Comment by JanProvaznik** [comment]
> If the install script hits this error, will it continue to work?
Likely no.
> Is this due to a lack of powershell policy?
Unclear, this error can appear in various scenarios.

**Comment by nagilson** [comment]
> Getting the same issue for about a week now. Tried installing different versions of .NET, and even reverted to the last month version, did not work. Please advise.
> 
> > Thank you for taking the time to write a detailed report. Is it true that `c:\Users\YOUR_USERNAME\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\8.0.10~x64~aspnetcore\dotnet.exe` does not exist? Of course replace your username.
> > Probably if you installed the .NET SDK (using our extension command to install .NET SDK 8.0.1xx) and restart vscode it would get rid of the error for you. Though not fix our bug 😄
> > -- [@dotnet/install-scripts-maintainers](https://github.com/orgs/dotnet/teams/install-scripts-maintainers)
> > ```
> > STDERR:  & : AuthorizationManager check failed.
> > At line:1 char:137
> > + ... ]::Tls12; & 'c:\Users\user\.vscode\extensions\ms-dotnettools.vsc ...
> > +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> >     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
> >     + FullyQualifiedErrorId : UnauthorizedAccess
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If the install script hits this error, will it continue to work? Is this due to a lack of powershell policy? It should be greater than ConstrainedLanguage or NoLanguage which I thought is all that is necessary.

As a workaround, can you install the .NET 8 aspnetcore runtime or .NET 8 sdk, then follow the guidance in the https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime&ssr=false#overview:~:text=I%20already%20have%20a%20.NET%20Runtime%20or%20SDK%20installed%2C%20and%20I%20want%20to%20use%20it 'I already have a .NET Runtime or SDK installed, and I want to use it' section.

**Comment by nagilson** [comment]
> > If the install script hits this error, will it continue to work?
> 
> Likely no.
> 
> > Is this due to a lack of powershell policy?
> 
> Unlikely, this error can appear in various scenarios.

Thank you @JanProvaznik  😄 Do you have any further context into how this error occurs? Should we try to get more information from the user so we can see if this is a bug that can be resolved?

**Comment by JanProvaznik** [comment]
Sorry, I don't have much insight my answer was based on a few quick searches. What is the invocation of install scripts in this project? It would be nice to have a minimal reproduction.

**Comment by easystreetgames** [comment]
I started having this problem yesterday also.  I am using VS Code with Unity.   I have not made any changes. It started displaying this message repeatedly in the Output panel: 
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

**Comment by sedat-eyuboglu** [comment]
I am getting same error in VS Code

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

**Comment by Kruille** [comment]
I believe they made a fatal error pointing the update to 8.0.10 when it is supposed to be 9.0.10. 
That was the only way to fix the issue. Install sdk 9.0.10. 
Or revert c# language installation and choose 8.0.483.

**Comment by sedat-eyuboglu** [comment]
I installed 8.0.10 by myself. The error message disappeared. Try to install underlined SDK version by yourself.

**Comment by JanProvaznik** [comment]
Could you tell me your system locales `Get-WinSystemLocale`? I realized this might be related: https://github.com/dotnet/install-scripts/issues/541

**Comment by easystreetgames** [comment]
I was also able to fix the problem by installing .NET 8.0.10 using this link: https://dotnet.microsoft.com/en-us/download/dotnet/8.0?form=MG0AV3.  Make sure to select the 8.0.10 version before downloading.  I am on Windows 11.

**Comment by MarkBennett** [comment]
I'm using the a devcontainer that builds our environment from the `mcr.microsoft.com/devcontainers/dotnet:dev-8.0-bookworm
` image and am seeing this error as of updating [the C# for Visual Studio Extension from Microsoft](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp).

Here's my complete Dockerfile for reference:

```
# Dotnet 8.0 Dev Container
FROM mcr.microsoft.com/devcontainers/dotnet:dev-8.0-bookworm

# Install SQL Tools: SQLPackage and sqlcmd
COPY mssql/installSQLtools.sh installSQLtools.sh
RUN bash ./installSQLtools.sh \
     && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts

USER vscode

# Setup Dotnet Dev Certs
RUN dotnet dev-certs https --trust

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

# Install Node Packages
RUN . /usr/local/share/nvm/nvm.sh \
     && nvm install 20 \
     && nvm use 20 \
     && npm install -g typescript azure-functions-core-tools@4 --unsafe-perm true
```

The C# extension is now failing to start with this output:

```
2024-11-14 16:46:41.674 [info] Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
2024-11-14 16:46:41.674 [info] No compatible .NET runtime found. Minimum required version is 8.0.10.
2024-11-14 16:46:45.657 [info] [Error - 4:46:45 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
2024-11-14 16:46:45.657 [info] Error: Could not resolve the dotnet path!
    at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.55.28-linux-arm64/dist/extension.js:2:1142621)
    at Generator.next (<anonymous>)
    at s (/home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.55.28-linux-arm64/dist/extension.js:2:1140600)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by nagilson** [comment]
For all of the new people commenting, that was a bug in the C# extension. Please update the C# extension for a fix. 

For the original comment, @JanProvaznik:
Heres the full command we called  (in the string parts we had)

```powershell.exe -NoProfile -NonInteractive -NoLogo -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; & "c:\Users\user\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\install scripts\dotnet-install.ps1" '-InstallDir', "c:\\Users\\user\\.vscode\\extensions\\ms-dotnettools.vscode-dotnet-runtime-2.2.2\\dist", '-Version', '8.0', '-Verbose', '-Runtime', 'aspnetcore'```

I provided some additional info on our internal memo based on the log which contains stderr, stdout, signal, status of the call.

**Comment by nagilson** [comment]
Do they have a log they can provide? Please see above for an example, or, our create new issue template explains how to get our log.
@bwateratmsft 

That is basically if everything looked fine but dotnet did not exist on the file system afterwards for some reason

**Comment by pamelafox** [comment]
@nagilson I've filed an issue with my logs here:
https://github.com/dotnet/vscode-dotnet-runtime/issues/2059

**Comment by RandyDotCom** [comment]
This is significantly blocking our team.

**Comment by nagilson** [comment]
Which version are you on? This should be fixed on 2.3.3 which just released. If that does not resolve the issue, I would expect the pre-release 2.3.4 to do so, but we have some delays on validation teams that have prevented that from being released yet.

**Comment by RandyDotCom** [comment]
Version: 1.99.3 (user setup)
Commit: 17baf841131aa23349f217ca7c570c76ee87b957
Date: 2025-04-15T23:18:46.076Z
Electron: 34.3.2
ElectronBuildId: 11161073
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by RandyDotCom** [comment]
winget upgrade --id Microsoft.VisualStudioCode
No available upgrade found.
No newer package versions are available from the configured sources.

**Comment by nagilson** [comment]
What is the version of the .NET Install Tool Extension is inside of VS Code? Thanks for finding that information, though it's not quite when I had meant, I did not specify very well. 

![Image](https://github.com/user-attachments/assets/a6b23ae8-edbc-4807-b11a-ff3499dfe22d)

**Comment by RandyDotCom** [comment]
Identifier
ms-dotnettools.vscode-dotnet-runtime
Version
2.3.3
Last Updated
2025-04-15, 20:13:40

**Comment by RandyDotCom** [comment]
found the installer dotnet-sdk-8.0.408-win-x64.exe  but that did not install in 
%AppData%\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet 

So I am unable to satisfy the request from: ms-azuretools.vscode-azure-github-copilot. 
This is blocking me from installing any .NET sdk's

**Comment by RandyDotCom** [comment]
deleted the lock and rebooted as suggested by the Error after 60001 retry's 
No Joy.

**Comment by nagilson** [comment]
Ah... this is a different issue I believe. Partially an issue on the copilot extension (not calling the findPath api to find your dotnet) but also partially on us for not having the feature that they would want to do that more efficiently in a json file.

@RandyDotCom A good work around for you would be to set this setting to your dotnet path:
'"dotnetAcquisitionExtension.sharedExistingDotnetPath": "/usr/share/dotnet/dotnet"'
(its also in our extension settings.)

I'm also hoping to release 2.3.4 (pre-release) today and that may also resolve your issue.

**Comment by nagilson** [comment]
If you need help, or others experience the same issue in the latest version, please file a new issue and I'm happy to work with you.
