### ISSUE TITLE
issue dotnet vscode report

### ISSUE THREAD

**Issue by leozimgranny** [dotnet/vscode-dotnet-runtime#2019]
Please attach the log file located at c:\Users\LeozimGranny\AppData\Roaming\Code\logs\20241113T002044\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1731468052931.txt. Note that this file may contain personal data.

**Extension Version:** 1.0.0
**Error Message:** The requested and or resolved version is invalid.
**Error Stack:** Error: The requested and or resolved version is invalid.
	at t.VersionResolver.resolveVersion (c:\Users\LeozimGranny\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\extension.js:2:114800)
	at c:\Users\LeozimGranny\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\extension.js:2:114261
	at new Promise (<anonymous>)
	at t.VersionResolver.<anonymous> (c:\Users\LeozimGranny\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\extension.js:2:114217)
	at Generator.next (<anonymous>)
	at s (c:\Users\LeozimGranny\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\extension.js:2:112801)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
