### ISSUE TITLE
Cancelled Installation of .NET 8.0.10. The requested and or resolved version is invalid.

### ISSUE THREAD

**Issue by ndJaime** [dotnet/vscode-dotnet-runtime#2035]
This popped up during startup this morning suggesting I should create a ticket.  I suppose it's being triggered by some auto-setting, so I thought I'd at least do the courtesy of letting y'all know.  If you don't care, neither do I.

![Image](https://github.com/user-attachments/assets/81e04daa-313a-427f-adf9-407ac737ed22)

**Comment by CREFaulk** [comment]
I have this in the output
`2024-11-13 09:32:03.831 [info] Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
2024-11-13 09:32:03.831 [info] No compatible .NET runtime found. Minimum required version is 8.0.10.
2024-11-13 09:32:04.909 [info] [Error - 9:32:04 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
2024-11-13 09:32:04.909 [info] Error: Could not resolve the dotnet path!
    at t.DotnetRuntimeExtensionResolver.<anonymous> (/Users/xxxxxxxxxx/.vscode/extensions/ms-dotnettools.csharp-2.55.28-darwin-arm64/dist/extension.js:2:1142621)
    at Generator.next (<anonymous>)
    at s (/Users/xxxxxxxx/.vscode/extensions/ms-dotnettools.csharp-2.55.28-darwin-arm64/dist/extension.js:2:1140600)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
