### ISSUE TITLE
No compatible .NET runtime found. Minimum required version is 8.0.10 and Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.

### ISSUE THREAD

**Issue by longnghg** [dotnet/vscode-dotnet-runtime#2046]
### Describe the bug.

Please attach the log file located at c:\Users\nghgl\AppData\Roaming\Cursor\logs\20241114T204358\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1731591842275.txt. Note that this file may contain personal data.

**Extension Version:** 1.0.0
**Error Message:** The requested and or resolved version is invalid.
**Error Stack:** Error: The requested and or resolved version is invalid.
	at t.VersionResolver.resolveVersion (c:\Users\anonymous\.cursor\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\extension.js:2:114800)
	at c:\Users\anonymous\.cursor\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\extension.js:2:114261
	at new Promise (<anonymous>)
	at t.VersionResolver.<anonymous> (c:\Users\anonymous\.cursor\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\extension.js:2:114217)
	at Generator.next (<anonymous>)
	at s (c:\Users\anonymous\.cursor\extensions\ms-dotnettools.vscode-dotnet-runtime-2.2.2\dist\extension.js:2:112801)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Please attach log file(s) here if you have any.

I cannot  go to reference implement function .net code and it's also not direct me to the function when press ctrl + left click 

### Reproduction Steps

Just open cursor IDE at 2024/11/14

### Expected Behavior

It work well

### .NET Install Tool Version

v2.2.2

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

**Comment by nagilson** [comment]
please see https://github.com/dotnet/vscode-dotnet-runtime/issues/2021
