### ISSUE TITLE
Error acquiring .NET runtime - VSCode Ubuntu 20.10

### ISSUE THREAD

**Issue by mrcteacher** [dotnet/vscode-dotnet-runtime#208]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** The "args" argument must be of type object. Received type string ('--info')
**Error Stack:** TypeError [ERR_INVALID_ARG_TYPE]: The "args" argument must be of type object. Received type string ('--info')
	at normalizeSpawnArguments (child_process.js:425:11)
	at Object.spawnSync (child_process.js:575:16)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67942)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64437
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64211)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67865
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:195071)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:193638
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:193412)
	at Object.t.callWithErrorHandling (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:195019)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67839)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64437
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64211)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67797
	at S._executeContributedCommand (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)
	at S._doExecuteCommand (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:105915)
	at S.executeCommand (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:105821)
	at Object.executeCommand (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:21932)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.blazorwasm-companion-1.0.0/dist/acquireDotnetInstall.js:29:35)
	at Generator.next (<anonymous>)
	at fulfilled (/home/anonymous/.vscode/extensions/ms-dotnettools.blazorwasm-companion-1.0.0/dist/acquireDotnetInstall.js:9:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by mrcteacher** [comment]
App runs fine, but cannot debug

**Comment by sfoslund** [comment]
@captainsafia I believe this is an issue with how the blazor extension is calling into the ensureDotnetDependencies command: https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/acquireDotnetInstall.ts#L23. We expect the arguments passed in IDotnetEnsureDependenciesContext to be of type `cp.SpawnSyncOptionsWithStringEncoding`, and you're passing a string: https://github.com/dotnet/vscode-dotnet-runtime/blob/976e80efc036f326c58163d39fbfbd1c24064e46/vscode-dotnet-runtime-library/src/IDotnetEnsureDependenciesContext.ts

Also, I would suggest wrapping this call in some sort of try catch to produce a better error message and since a failure on this command does not necessarily mean that the rest of the install has failed.

**Comment by captainsafia** [comment]
@sfoslund You can transfer this issue to the aspnetcore repo for tracking there.
