### ISSUE TITLE
Debug of wasm stop working

### ISSUE THREAD

**Issue by kattunga** [dotnet/vscode-dotnet-runtime#212]
I can't debug dotnet wasm anymore since last version.

Ubuntu 20.04

Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-49-generic snap

**Repro steps:**

Error message

1.

**Extension Version:** 1.0.0
**Error Message:** The "args" argument must be of type object. Received type string ('--info')
**Error Stack:** TypeError [ERR_INVALID_ARG_TYPE]: The "args" argument must be of type object. Received type string ('--info')
	at normalizeSpawnArguments (child_process.js:425:11)
	at Object.spawnSync (child_process.js:575:16)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67942)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64437
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64211)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67865
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:195071)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:193638
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:193412)
	at Object.t.callWithErrorHandling (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:195019)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67839)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64437
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64211)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67797
	at S._executeContributedCommand (/snap/code/62/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)
	at S._doExecuteCommand (/snap/code/62/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:105915)
	at S.executeCommand (/snap/code/62/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:105821)
	at Object.executeCommand (/snap/code/62/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:21932)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.blazorwasm-companion-1.0.0/dist/acquireDotnetInstall.js:29:35)
	at Generator.next (<anonymous>)
	at fulfilled (/home/anonymous/.vscode/extensions/ms-dotnettools.blazorwasm-companion-1.0.0/dist/acquireDotnetInstall.js:9:58)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)

[DotNetAcquisition1618487005616.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/6317624/DotNetAcquisition1618487005616.txt)

**Comment by kattunga** [comment]
This problem happens since "Blazor WASM Debugging Extension" was installed.

The Blazor WASM Debugging Extension is required to debug Blazor WASM apps in VS Code.

**Comment by NTaylorMullen** [comment]
FYI @captainsafia

**Comment by captainsafia** [comment]
We're tracking this in https://github.com/dotnet/aspnetcore/issues/31757.

**Comment by kattunga** [comment]
Is there any known workarround?
By the moment the only solution that I found is to use a combination of code-insiders with a previous c# extension (version 1.23.9)

**Comment by sfoslund** [comment]
Closing as a dup for dotnet/aspnetcore#31757.
