### ISSUE TITLE
.Net Acquisition failed

### ISSUE THREAD

**Issue by artcolman** [dotnet/vscode-dotnet-runtime#230]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install scripts\dotnet-install.ps1 : 
Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the file 
'C:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\3.1.15\dotnet.exe' 
because it is being used by another process."
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dotnet-install.ps1], MethodInvocationException
    + FullyQualifiedErrorId : IOException,dotnet-install.ps1
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install scripts\dotnet-install.ps1 : 
Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the file 
'C:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\3.1.15\dotnet.exe' 
because it is being used by another process."
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dotnet-install.ps1], MethodInvocationException
    + FullyQualifiedErrorId : IOException,dotnet-install.ps1
 

	at c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\extension.js:2:13753
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by heartacker** [comment]
Downloading the .NET Runtime.
Downloading .NET version(s) 5.0.7 .............................................................................................................. Error!
Failed to download .NET 5.0.7:
.NET installation timed out.

 Error!
.NET Acquisition Failed: Installation failed: Error: .NET installation timed out.
