### ISSUE TITLE
Bicep having issues loading .Net 5

### ISSUE THREAD

**Issue by gaknowles** [dotnet/vscode-dotnet-runtime#239]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: & : File C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1 cannot be loaded because its operation is blocked by software restriction policies, such as 
those created by using Group Policy.
At line:1 char:138
+ ... ::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: & : File C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1 cannot be loaded because its operation is blocked by software restriction policies, such as 
those created by using Group Policy.
At line:1 char:138
+ ... ::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

	at c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\extension.js:2:13753
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

Please attach the log file located at c:\Users\GaryK\AppData\Roaming\Code\logs\20210606T150017\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1623017055992.txt. Note that this file may contain personal data.

The request log file was empty.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by sfoslund** [comment]
> dotnet-install.ps1 cannot be loaded because its operation is blocked by software restriction policies, such as
those created by using Group Policy.

@gaknowles do you have software restriction policies in place on your machine?

**Comment by gaknowles** [comment]
Not to the best of my knowledge. This is a personal machine with a vanilla install
