### ISSUE TITLE
ms-dotnettools.vscode-dotnet-runtime-1.2.0 fails on Mac M1

### ISSUE THREAD

**Issue by Vikas413** [dotnet/vscode-dotnet-runtime#265]
**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.17" -Version 3.1.17 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.17
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.17" -Version 3.1.17 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.17
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

	at /Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/extension.js:2:13778

**Comment by sfoslund** [comment]
Hmm this is odd, 3.1.17 should be a valid version. Is this error happening regularly?

**Comment by tedsecretsource** [comment]
Same here, exactly.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.17" -Version 3.1.17 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.17
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.17" -Version 3.1.17 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.17
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

	at /Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/extension.js:2:13778

**Comment by spouliot** [comment]
This happens because it's a M1-based Mac and it's looking, by default, for an `arm64` package.
However 3.1 (and 5.0) do not support `arm64` and should be using `x64` packages (that Rosetta will accept and execute).

This should be _fixed_ with net6 as there are `arm64` packages available for macOS.

**Comment by sschultze** [comment]
I ran into the same issue: https://github.com/dotnet/vscode-dotnet-runtime/issues/300

**Comment by sschultze** [comment]
I have to use the x64 version of .NET even if on Apple Silicon because I use a native x64-only third-party library.

What I found is that as soon as I install an arm64 version of .NET 6 in parallel to, for example, an x64 version of .NET 5, things get really bad. The arm64 version installs an arm64-only dotnet executable which cannot load the x64 .NET 5 stuff.

So I have to avoid installing an arm64 of .NET.

In my opinion, there should be a way to configure the architecture that this extension installs .NET versions for, because there doesn't seem to be a concept for mixed installations of .NET architectures. (Or I haven't found it.)

**Comment by tonidy** [comment]
> In my opinion, there should be a way to configure the architecture that this extension installs .NET versions for, because there doesn't seem to be a concept for mixed installations of .NET architectures. (Or I haven't found it.)

I agree with @sschultze's comment. The extension should have setting to change the architecture from `arm64` to `x64` in Apple Silicon.

Currently I'm using this workaround:

```sh
user@mbp ms-dotnettools.vscode-dotnet-runtime % ./dotnet-install.sh --arch x64 --install-dir .dotnet/7.0.8 --runtime dotnet --version 7.0.8
```
