### ISSUE TITLE
MacOs 12.1 - M1 Pro - VS Code Insiders startup error - Could not find .NET Core Runtime with version = 3.1.22

### ISSUE THREAD

**Issue by mbatesco** [dotnet/vscode-dotnet-runtime#370]
**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.22" -Version 3.1.22 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.22
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.22" -Version 3.1.22 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.22
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

    at /Users/anonymous/.vscode-insiders/extensions/vscode-dotnet-runtime-library/dist/Acquisition/DotnetCoreAcquisitionWorker.js:89:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

This file /Users/mbates/Library/Application Support/Code - Insiders/logs/20211219T080359/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1639929926008.txt is empty.

**Repro steps:**

1. Start VS Code Insiders on Mac M1 Pro - Monterey 12.1 and I get the error

Version: 1.64.0-insider (Universal)
Commit: d12df34e31b4a018735d312a8947d79331132368
Date: 2021-12-17T05:14:21.805Z (2 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

This solution does not help: "dotnetAcquisitionExtension.installTimeoutValue": 180

I have .NET  version installed.

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

**Comment by mbatesco** [comment]
I did some work to figure out the extension  Visual Studio Intellicode Insiders 1.1.5 causes the issue. When I remove it, restart the error does not display. On install the error comes up.  

If this is the incorrect place for this issue, let me know the correct one and I'll get it reported there.

Mike
