### ISSUE TITLE
Installing bicep extension is WSL2 environment faile

### ISSUE THREAD

**Issue by dumbnose** [dotnet/vscode-dotnet-runtime#401]
The issue text was copied to the clipboard.  Please paste it into this window.

**Repro steps:**

1. Launch .net project using code . in a WSL2 window
2. Open bicep file and click 'install' when prompted

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.2" -Version 6.0.2 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.2" -Version 6.0.2 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/extension.js:2:13750
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

Please attach the log file located at /home/jsheehan/.vscode-server/data/logs/20220223T115128/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1645645974587.txt. Note that this file may contain personal data.

THIS FILE WAS EMPTY 

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by hansmbakker** [comment]
it looks like `/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh` is actually a powershell script which is not meant to be run in WSL2... super weird

**Comment by hansmbakker** [comment]
this is a duplicate of #309
