### ISSUE TITLE
An error occurred while installing .NET: .NET Acquisition Failed: Installation failed

### ISSUE THREAD

**Issue by Meligy** [dotnet/vscode-dotnet-runtime#957]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /Users/meligy/Library/Application Support/Code - Insiders/logs/20230623T135805/window4/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1687492690395.txt. Note that this file may contain personal data.

> ## Answer: 
> The file is empty

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.8" -Version 7.0.8 -Runtime dotnet

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.8" -Version 7.0.8 -Runtime dotnet

	at /Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:4766

**Comment by Meligy** [comment]
Also got it apparently repeated, again with empty text file:

The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /Users/meligy/Library/Application Support/Code - Insiders/logs/20230623T135805/window4/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1687492690395.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement



**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.8" -Version 7.0.8 -Runtime dotnet

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.8" -Version 7.0.8 -Runtime dotnet

	at /Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:4766
