### ISSUE TITLE
[Error - 14:40:29] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server. Error: Could not resolve the dotnet path!

### ISSUE THREAD

**Issue by Eduard0MS** [dotnet/vscode-dotnet-runtime#958]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\Eduardo\AppData\Roaming\Code\logs\20230623T143625\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1687542019260.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by Vandanabatchu** [comment]
[Error - 3:57:50 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Could not resolve the dotnet path!
    at t.DotnetRuntimeExtensionResolver.<anonymous> (c:\Users\pavan\.vscode\extensions\ms-dotnettools.csharp-2.0.328-win32-x64\dist\extension.js:2:1407951)
    at Generator.next (<anonymous>)
    at s (c:\Users\pavan\.vscode\extensions\ms-dotnettools.csharp-2.0.328-win32-x64\dist\extension.js:2:1406556)
